#!/bin/bash

vers=23.05

set -e -x

sh <(curl -L https://nixos.org/nix/install) --no-daemon
# shellcheck disable=SC1090,SC1091
source "$HOME/.nix-profile/etc/profile.d/nix.sh"
nix-channel --remove nixpkgs
nix-channel --add "https://nixos.org/channels/nixos-${vers}" "nixpkgs"
nix-channel --update -v
nix-env -iA nixpkgs.nix
nix-env -u
if [ "$vers" = unstable ]; then
    nix-channel --add "https://github.com/nix-community/home-manager/archive/master.tar.gz" home-manager
else
    nix-channel --add "https://github.com/nix-community/home-manager/archive/release-${vers}.tar.gz" home-manager
fi
nix-channel --update -v
export NIX_PATH=${NIX_PATH:+$NIX_PATH:}$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels
nix-shell '<home-manager>' -A install
rm -f ~/.config/home-manager/home.nix ~/.config/nixpkgs/home.nix
home-manager switch -v

